spring:
  config:
    import: env.properties
  profiles:
    active: ${ACTIVE}
  h2:
    console:
      enabled: true
      settings:
        trace: false
server:
  port: ${PORT}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root:
    com:
    org:

api:
  version: /api/v0

---
spring:
  config:
    activate:
      on-profile: dev
    import: optional:secrets.properties[.properties]
  sql:
    init:
      mode: always

  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: ${LOCAL_DRIVER_CLASS_NAME}
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
                format_sql: true
      dialect: ${LOCAL_JPA_DIALECT}
      generate_statistics: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
---
spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: always

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
    driver_class_name: ${DEV_DRIVER_CLASS_NAME}
  jpa:
    database: mysql
    defer_datasource_initialization: false
    properties:
      hibernate:
        dialect: ${DEV_JPA_DIALECT}
        generate_ddl: true
      generate_statistics: false
    show_sql: false
    hibernate:
      ddl_auto: update
---
spring:
  config:
    activate:
      on-profile: test
    import: optional:secrets.properties[.properties]
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: ${TEST_DRIVER_CLASS_NAME}
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
