application:
  security:
    jwt:
      secret-key: de0753b0c76cb52a812e520f7b39c8dbd6f3ac463ee414d71f3e613afbaed48a
      expiration: 60000
      refresh-token:
        expiration: 300000
#      expiration: 86400000
#      refresh-token:
#        expiration: 604800000
---
spring:
  config:
    import: env.properties
  profiles:
    active: ${ACTIVE}
  h2:
    console:
      enabled: true
      settings:
        trace: false

server:
  port: ${PORT}
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
logging:
  level:
    root:
    com:
    org:

api:
  version: /api/v0

---
spring:
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USER}
    password: ${DEV_DB_PASSWORD}
    driver_class_name: ${DEV_DRIVER_CLASS_NAME}
  jpa:
    database: mysql
    defer_datasource_initialization: true
    properties:
      hibernate:
        dialect: ${DEV_JPA_DIALECT}
        generate_ddl: true
      generate_statistics: false
    show_sql: false
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: danittest2@gmail.com
    password: aumlfjunalzwdrss
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

---
spring:
  config:
    activate:
      on-profile: test
    import: optional:secrets.properties[.properties]
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
  datasource:
    url: ${TEST_DB_URL}
    username: ${TEST_DB_USER}
    password: ${TEST_DB_PASSWORD}
    driver-class-name: ${TEST_DRIVER_CLASS_NAME}
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: danittest2@gmail.com
    password: aumlfjunalzwdrss
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
#/*
# TODO ddl-auto  глянкти можливі варіанти
#  TODO анотація Component
#  допомогла розібратися https://stackoverflow.com/questions/68711396/org-springframework-beans-factory-beancreationexception-error-creating-bean-wit
#
#  */